In [1]:
import pandas as pd
import numpy as np
from astroquery.mast import Observations

In [2]:
def find_tic(kic):
    # supply KIC
    # restrict the mission to TESS
    # had to search by radius. Only produced results other than FFI around 0.2 degrees 
    # How valid is this join?
    objectname = "KIC " + str(kic)
    obs_table = Observations.query_criteria(objectname=objectname, radius=".2 deg", obs_collection="TESS")
    obs_table = obs_table[obs_table["target_name"]!="TESS FFI"] # remove "TESS FFI results"
    if len(obs_table) > 0:
        return obs_table[0]["target_name"]
    else:
        return "N/A"

In [3]:
df = pd.read_csv("full_tce_list.csv")
df.head(10)

,TCE_ID,rv_score,disposition,not_transit,stellar_eclipse,centroid_offset,ephemeris,other,Data_Set,KIC,...,alb_alt,alb_alt_perr,alb_alt_merr,mod_depth_pri_alt,mod_depth_sec_alt,mod_ph_sec_alt,mod_ph_ter_alt,sdepthsig_dv,sdepthsig_alt,radius_ratio
0,000757099-01,0.000,FP,1,0,0,0,LPP_DV---LPP_ALT---MOD_NONUNIQ_DV,OBS,757099,...,0.795,0.941,0.384,0.001129,0.000402,0.540894,0.000000,0.000000,0.000000,1.076020
1,000757450-01,0.999,PC,0,0,0,0,NaN,OBS,757450,...,2.457,0.574,0.579,0.015339,0.000094,0.405275,0.769840,0.168748,0.113356,0.080825
2,000892376-01,0.000,FP,1,0,0,0,INDIV_TRANS_CHASES_MARSHALL---LPP_DV---ALL_TRA...,OBS,892376,...,20564.039,15540.262,6765.046,0.000820,0.000309,0.627224,0.404876,-1.000000,-1.000000,0.305556
3,000892376-02,0.000,FP,1,0,0,0,LPP_DV---MOD_NONUNIQ_DV---CENT_KIC_POS,OBS,892376,...,12.150,9.061,4.186,0.000111,0.000030,0.504963,0.000000,0.016516,0.033440,0.876812
4,000892376-03,0.000,FP,1,0,0,0,INDIV_TRANS_RUBBLE---TRANS_GAPPED---LPP_DV---L...,OBS,892376,...,2766.420,26284.655,2185.186,0.001205,0.000971,0.713854,0.856854,-1.000000,-1.000000,0.123975
5,000892376-04,0.000,FP,1,0,0,0,INDIV_TRANS_RUBBLE_CHASES_MARSHALL---LPP_DV---...,OBS,892376,...,76350.330,557843.410,57444.288,0.001447,0.004384,0.909749,0.911610,-1.000000,-1.000000,0.110000
6,000892376-05,0.000,FP,1,0,0,0,INDIV_TRANS_RUBBLE---TRANS_GAPPED---LPP_DV---L...,OBS,892376,...,47631.028,70768.627,21889.876,0.002008,0.002940,0.334042,0.115254,-1.000000,-1.000000,0.347701
7,000892376-06,0.000,FP,1,0,0,0,INDIV_TRANS_RUBBLE_SKYE---TRANS_GAPPED---LPP_D...,OBS,892376,...,4907.320,69700.550,3671.734,0.000853,0.003033,0.851404,0.107312,-1.000000,-1.000000,0.122222
8,000892667-01,0.000,FP,1,0,0,0,LPP_DV,OBS,892667,...,0.000,0.331,0.592,0.000161,0.000000,0.496062,0.000000,0.120810,0.213151,1.817582
9,000892772-01,0.000,FP,0,0,1,0,CENT_RESOLVED_OFFSET---HALO_GHOST,OBS,892772,...,39.126,73.350,20.964,0.000239,0.000043,0.523557,0.077867,0.309856,0.413671,0.528873

In [4]:
df = df.rename(columns={"KIC": "kic"})

In [8]:
df.head(10)["kic"]

0    757099
1    757450
2    892376
3    892376
4    892376
5    892376
6    892376
7    892376
8    892667
9    892772
Name: kic, dtype: int64

In [9]:
len(df["kic"].unique())

16736

In [10]:
df.head(10)["kic"].apply(find_tic)

0    122678660
1    122678660
2    137099260
3    137099260
4    137099260
5    137099260
6    137099260
7    137099260
8    122678660
9    122784501
Name: kic, dtype: object

In [11]:
df_tic = pd.read_csv("CTL_v8_ExoFOP-TESS.csv", usecols=["id", "kic"])

/Users/deanwang/anaconda3/envs/triceratops/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (0,10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [12]:
df_tic.head()

         id  kic
0      long  int
1       NaN  NaN
2       NaN  NaN
3  38511816  NaN
4  38511909  NaN

In [13]:
df_tic = df_tic[3:]

In [14]:
df_tic

                id  kic
3         38511816  NaN
4         38511909  NaN
5         89111222  NaN
6         89112040  NaN
7         89146939  NaN
...            ...  ...
9488280  276657783  NaN
9488281  276659863  NaN
9488282  367168632  NaN
9488283  375004134  NaN
9488284  375010308  NaN

[9488282 rows x 2 columns]

In [15]:
len(df_tic["id"].unique())

9488282

In [16]:
len(df_tic["kic"].unique())

122967

In [17]:
df.set_index("kic").join(df_tic.set_index("kic"), on="kic", lsuffix='_tce', rsuffix='_tic')

,TCE_ID,rv_score,disposition,not_transit,stellar_eclipse,centroid_offset,ephemeris,other,Data_Set,pn,...,alb_alt_perr,alb_alt_merr,mod_depth_pri_alt,mod_depth_sec_alt,mod_ph_sec_alt,mod_ph_ter_alt,sdepthsig_dv,sdepthsig_alt,radius_ratio,id
kic,,,,,,,,,,,,,,,,,,,,,
757099,000757099-01,0.000,FP,1,0,0,0,LPP_DV---LPP_ALT---MOD_NONUNIQ_DV,OBS,1,...,0.941,0.384,0.001129,0.000402,0.540894,0.000000,0.000000,0.000000,1.076020,122785244
757450,000757450-01,0.999,PC,0,0,0,0,NaN,OBS,1,...,0.574,0.579,0.015339,0.000094,0.405275,0.769840,0.168748,0.113356,0.080825,NaN
892376,000892376-01,0.000,FP,1,0,0,0,INDIV_TRANS_CHASES_MARSHALL---LPP_DV---ALL_TRA...,OBS,1,...,15540.262,6765.046,0.000820,0.000309,0.627224,0.404876,-1.000000,-1.000000,0.305556,NaN
892376,000892376-02,0.000,FP,1,0,0,0,LPP_DV---MOD_NONUNIQ_DV---CENT_KIC_POS,OBS,2,...,9.061,4.186,0.000111,0.000030,0.504963,0.000000,0.016516,0.033440,0.876812,NaN
892376,000892376-03,0.000,FP,1,0,0,0,INDIV_TRANS_RUBBLE---TRANS_GAPPED---LPP_DV---L...,OBS,3,...,26284.655,2185.186,0.001205,0.000971,0.713854,0.856854,-1.000000,-1.000000,0.123975,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12885212,012885212-01,0.001,FP,0,0,1,0,CENT_RESOLVED_OFFSET,OBS,1,...,12.196,3.884,0.000320,0.000038,0.442287,0.713401,0.445814,0.460570,0.493960,NaN
12885212,012885212-02,0.638,PC,0,0,0,0,NaN,OBS,2,...,12247.123,1068.208,0.000840,0.000268,0.366811,0.534503,0.549336,0.101915,0.217109,NaN
12885505,012885505-01,0.000,FP,1,0,0,0,INDIV_TRANS_MARSHALL---LPP_DV---INCONSISTENT_T...,OBS,1,...,63379.154,8693.629,0.000148,0.000073,0.917918,0.804026,-1.000000,-1.000000,0.583803,406952657
12935144,012935144-01,0.000,FP,0,0,1,0,CENT_RESOLVED_OFFSET---HALO_GHOST,OBS,1,...,9.736,1.343,0.000261,0.000024,0.836015,0.587757,0.140447,0.161009,0.543871,NaN
100001645,100001645-01,0.000,FP,1,0,0,0,LPP_DV---LPP_ALT---ALL_TRANS_CHASES---MOD_NONU...,OBS,1,...,3287.443,322.182,0.001170,0.001310,0.649599,0.039862,-1.000000,-1.000000,0.079554,NaN

In [18]:
df.set_index("kic").join(df_tic.set_index("kic"), on="kic", how="inner", lsuffix='_tce', rsuffix='_tic')

,TCE_ID,rv_score,disposition,not_transit,stellar_eclipse,centroid_offset,ephemeris,other,Data_Set,pn,...,alb_alt_perr,alb_alt_merr,mod_depth_pri_alt,mod_depth_sec_alt,mod_ph_sec_alt,mod_ph_ter_alt,sdepthsig_dv,sdepthsig_alt,radius_ratio,id
kic,,,,,,,,,,,,,,,,,,,,,
757099,000757099-01,0.0,FP,1,0,0,0,LPP_DV---LPP_ALT---MOD_NONUNIQ_DV,OBS,1,...,0.941,0.384,0.001129,0.000402,0.540894,0.000000,0.000000,0.000000,1.076020,122785244
892667,000892667-01,0.0,FP,1,0,0,0,LPP_DV,OBS,1,...,0.331,0.592,0.000161,0.000000,0.496062,0.000000,0.120810,0.213151,1.817582,122785148
1025986,001025986-01,0.0,FP,1,0,0,0,INDIV_TRANS_CHASES_SKYE---CENT_SATURATED,OBS,1,...,13222.917,1432.482,0.000138,0.000022,0.976804,0.019950,-1.000000,-1.000000,0.554673,122784720
1026133,001026133-01,0.0,FP,1,0,0,0,SWEET_NTL---LPP_DV---LPP_ALT---MOD_NONUNIQ_ALT,OBS,1,...,4.130,7.458,0.000058,0.000000,0.503603,0.000000,0.091493,0.143307,1.755435,122784832
1026133,001026133-02,0.0,FP,1,0,0,0,INDIV_TRANS_RUBBLE_MARSHALL---TRANS_GAPPED---L...,OBS,2,...,3884.454,1777.343,0.000244,0.000139,0.713100,0.987499,-1.000000,-1.000000,0.553082,122784832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12884588,012884588-01,0.0,FP,1,0,0,0,LPP_DV---LPP_ALT---CENT_FEW_DIFFS,OBS,1,...,0.977,5.366,0.000022,0.000000,0.599988,0.000000,0.070418,0.047871,2.204412,416279612
12885086,012885086-01,0.0,FP,1,0,0,0,LPP_DV---LPP_ALT---MOD_NONUNIQ_DV---MOD_NONUNI...,OBS,1,...,1.684,0.711,0.000025,0.000022,0.668083,0.335452,0.019672,0.030626,1.755385,267744690
12885086,012885086-02,0.0,FP,1,0,0,0,INDIV_TRANS_RUBBLE_SKYE_ZUMA---TRANS_GAPPED---...,OBS,2,...,8.897,4.256,0.000067,0.000050,0.426869,0.841472,0.159012,0.085257,1.391463,267744690
12885086,012885086-03,0.0,FP,1,0,0,0,INDIV_TRANS_RUBBLE_SKYE_ZUMA---TRANS_GAPPED---...,OBS,3,...,1.628,2.296,0.000042,0.000000,0.400166,0.000000,0.567764,0.117278,1.326744,267744690
12885505,012885505-01,0.0,FP,1,0,0,0,INDIV_TRANS_MARSHALL---LPP_DV---INCONSISTENT_T...,OBS,1,...,63379.154,8693.629,0.000148,0.000073,0.917918,0.804026,-1.000000,-1.000000,0.583803,406952657

In [19]:
df_joined = df.set_index("kic").join(df_tic.set_index("kic"), on="kic", how="inner", lsuffix='_tce', rsuffix='_tic')

In [20]:
len(df_joined.index.unique())

5675

In [21]:
len(df_joined["id"].unique())

5675

In [22]:
df_joined = df_joined.rename(columns={"id": "tic"})

In [25]:
df_joined[["tic"]].to_csv("joined.csv")